[udp]
host = "255.255.255.255"
port = "1998"

[tcp]
host = "0.0.0.0"
port = "1996"

[http]
host = "0.0.0.0"
port = "1997"

[websocket]
host = "0.0.0.0"
port = "1999"

[log]
level = "debug"
dir = "logs"
format = "text"
to = "stdout"